image: nikolaik/python-nodejs:python3.10-nodejs20

include:
  - project: geoplateforme/templates
    ref: main
    file:
      - "ci/docker-v5.yml"
      - "ci/chart-v2.yml"
      - "ci/versioning.yml"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - when: always

cache:
  paths:
    - node_modules/

lint:
  before_script:
    - npm ci
  script:
    - npm run lint

test:
  before_script:
    - apt-get update && apt-get install -y p7zip-full
    - npm ci
  script:
    - npm run test-lcov
  artifacts:
    paths:
      - coverage/lcov.info
    expire_in: 1 week

test:recette:
  before_script:
    - npm ci
  script:
    - npm run test-recette
  when: manual

test:recette-batch:
  before_script:
    - npm ci
  script:
    - npm run test-recette-batch
  when: manual

pages:
  stage: deploy
  when: manual
  script:
    - python -m pip install -U virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - python -m pip install -U pip
    - python -m pip install -U setuptools wheel
    - python -m pip install -U -r requirements-mkdocs.txt
    - mkdocs build --strict --verbose -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
