services:
  api:
    build: .
    command: npm run api:start
    ports:
      - "3000:3000"
    environment:
      ADDRESS_INDEX_URL: http://address:3000
      PARCEL_INDEX_URL: http://parcel:3000
      POI_INDEX_URL: http://poi:3000
      REDIS_URL: redis://redis:6379
      STORAGE_FS_DIR: /app/storage/
      MAGIC_TOKEN: "12345"
    volumes:
      - shared-storage:/app/storage
  redis:
    image: redis:7-alpine
  worker:
    build: .
    command: npm run worker:start
    environment:
      ADDRESS_INDEX_URL: http://address:3000
      PARCEL_INDEX_URL: http://parcel:3000
      POI_INDEX_URL: http://poi:3000
      REDIS_URL: redis://redis:6379
      STORAGE_FS_DIR: /app/storage/
    volumes:
      - shared-storage:/app/storage
  address:
    build: .
    command: bash -c "npm run address:download-index && npm run address:start"
    environment:
      ADDRESS_ARCHIVE_URL_RESOLVER: https://gpf-prepared-data.s3.sbg.io.cloud.ovh.net/sample-57-index-address-latest
  parcel:
    build: .
    command: bash -c "npm run parcel:download-index && npm run parcel:start"
    environment:
      PARCEL_ARCHIVE_URL_RESOLVER: https://gpf-prepared-data.s3.sbg.io.cloud.ovh.net/sample-57-index-parcel-latest
  poi:
    build: .
    command: bash -c "npm run poi:download-index && npm run poi:start"
    environment:
      POI_ARCHIVE_URL_RESOLVER: https://gpf-prepared-data.s3.sbg.io.cloud.ovh.net/sample-57-index-poi-latest

volumes:
  shared-storage:
